
USE kiceo_db;

-- SUPPRIMER les tables avant d'insérer de nouvelles données afin d'éviter les entrées en double.
DELETE FROM Horaire;
DELETE FROM Station;
DELETE FROM Ligne;
DELETE FROM Jour;
DELETE FROM Desservir;
DELETE FROM Circuler;
DELETE FROM Planifier;
DELETE FROM Attribuer;

-- Remplir "Jour" et "Ligne" avec les données fixes pour le lundi et la ligne 2
INSERT INTO Jour (name) VALUES ('Lundi');
SET @jour_lundi = LAST_INSERT_ID();

INSERT INTO Ligne (name) VALUES ('Ligne 2 P+R Ouest - Kersec');
SET @ligne_2 = LAST_INSERT_ID();

-- Établir la relation entre la ligne 2 et le lundi
INSERT INTO Circuler (ligne_id, jour_id) VALUES (@ligne_2, @jour_lundi);

-- Maintenant, on remplis "Station" et "Horaire", puis on créer les relations à l'aide des tables d'association.

INSERT INTO Station (name) VALUES ('P+R Ouest');
SET @station_id = LAST_INSERT_ID();
INSERT INTO Desservir (station_id, ligne_id) VALUES (@station_id, @ligne_2);
INSERT INTO Horaire (time) VALUES ('6:32');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('6:42');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('6:52');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:00');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:10');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);

INSERT INTO Station (name) VALUES ('Fourchene 1');
SET @station_id = LAST_INSERT_ID();
INSERT INTO Desservir (station_id, ligne_id) VALUES (@station_id, @ligne_2);
INSERT INTO Horaire (time) VALUES ('6:34');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('6:44');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('6:54');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:02');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:12');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);

INSERT INTO Station (name) VALUES ('Madelaine');
SET @station_id = LAST_INSERT_ID();
INSERT INTO Desservir (station_id, ligne_id) VALUES (@station_id, @ligne_2);
INSERT INTO Horaire (time) VALUES ('6:37');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('6:47');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('6:57');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:06');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:16');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);

INSERT INTO Station (name) VALUES ('République');
SET @station_id = LAST_INSERT_ID();
INSERT INTO Desservir (station_id, ligne_id) VALUES (@station_id, @ligne_2);
--INSERT INTO Horaire (time) VALUES ('6:42');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('6:52');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:02');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:12');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:22');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);

INSERT INTO Station (name) VALUES ('PIBS 2');
SET @station_id = LAST_INSERT_ID();
INSERT INTO Desservir (station_id, ligne_id) VALUES (@station_id, @ligne_2);
INSERT INTO Horaire (time) VALUES ('6:46');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('6:56');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:07');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:17');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:27');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);

INSERT INTO Station (name) VALUES ('Petit Tohannic');
SET @station_id = LAST_INSERT_ID();
INSERT INTO Desservir (station_id, ligne_id) VALUES (@station_id, @ligne_2);
INSERT INTO Horaire (time) VALUES ('6:50');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:00');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:11');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:21');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:31');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);

INSERT INTO Station (name) VALUES ('Delestraint');
SET @station_id = LAST_INSERT_ID();
INSERT INTO Desservir (station_id, ligne_id) VALUES (@station_id, @ligne_2);
INSERT INTO Horaire (time) VALUES ('6:51');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:01');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:12');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:22');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:32');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);

INSERT INTO Station (name) VALUES ('Kersec');
SET @station_id = LAST_INSERT_ID();
INSERT INTO Desservir (station_id, ligne_id) VALUES (@station_id, @ligne_2);
INSERT INTO Horaire (time) VALUES ('6:55');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:05');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:16');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:26');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
INSERT INTO Horaire (time) VALUES ('7:36');
SET @horaire_id = LAST_INSERT_ID();
INSERT INTO Planifier (horaire_id, jour_id) VALUES (@horaire_id, @jour_lundi);
INSERT INTO Attribuer (horaire_id, station_id) VALUES (@horaire_id, @station_id);
